### ISSUE TITLE
[JORGE ALBORS]- w3-Database-Project

### ISSUE THREAD

**Issue by JORGE-SAPIS** [Ironhack-Data-Madrid-Mayo-2022/w3-Database-Project#1]

**Comment by Gobuub** [comment]
Jorge el link va en un comentario no en el nombre de la issue, todavía estás a tiempo de corregirlo

**Comment by JORGE-SAPIS** [comment]
https://github.com/JORGE-SAPIS/DB-SQL.git

**Comment by Gobuub** [comment]
Buen trabajo Jorge poco más que añadir a lo que ya te dijimos durante la presentación.
