### ISSUE TITLE
[Mau Guerrero]w3-Database-Project

### ISSUE THREAD

**Issue by maugc1** [Ironhack-Data-Madrid-Mayo-2022/w3-Database-Project#2]
https://github.com/maugc1/Proyecto_2.git

**Comment by Gobuub** [comment]
Al final salió Mau, las cosas únicamente se consiguen con trabajo, no vienen dadas ;), tienes muy buenas cualidades, pero hay veces que te me dispersas :P, hay que ponerse las pilas. Son 10 semanas duras, pero que tendrán su recompensa si lo haces bien :). Ánimo.
