### ISSUE TITLE
[Javi Perez Vera] 'Proyecto creación base de datos'

### ISSUE THREAD

**Issue by JaviPerez23** [Ironhack-Data-Madrid-Mayo-2022/w3-Database-Project#3]
https://github.com/JaviPerez23/Proyecto-SQL.git

**Comment by Gobuub** [comment]
Me ha faltado el archivo con la base de datos completa para probar las queys, pero en general, te lo has currado, y te he visto hacerlo, poco a poco irás cogiéndole el punto a todo. Sigue así.
