### ISSUE TITLE
[Alex Dominguez] w3-Database-Project

### ISSUE THREAD

**Issue by adominguez033** [Ironhack-Data-Madrid-Mayo-2022/w3-Database-Project#5]
https://github.com/adominguez033/Project2_DA_Ironhack

**Comment by Gobuub** [comment]
Buen trabajo Alex, buena limpieza, muy bien organizado el repo, únicamente hecho en falta la base de datos exportada, para poder abrirla directamente y no tener que crearla desde las querys, pero bueno así se ve si funcionan o no.
