### ISSUE TITLE
[Oriana Ampuero] w3-Database-Project

### ISSUE THREAD

**Issue by OrianAmpuero** [Ironhack-Data-Madrid-Mayo-2022/w3-Database-Project#6]
https://github.com/OrianAmpuero/PROJECT-MOVIES.git

**Comment by Gobuub** [comment]
Ya hablamos esta mañana del tema Oriana :), lo importante es que poco a poco vayas cogiéndole el truco, sql es complicado aprenderlo en una semana, pero lo importante como has dicho muchas veces es pillar el 10% ;).
Sigue así, que vas bien.
