### ISSUE TITLE
[Lucía Martín] w3-Database-Project

### ISSUE THREAD

**Issue by luciaahab** [Ironhack-Data-Madrid-Mayo-2022/w3-Database-Project#8]
https://github.com/luciaahab/blockbuster.git

**Comment by Gobuub** [comment]
Un poco de caos en la organización del repo XDD, con lo bien estructurado que lo tenías la semana pasada este no has separado los archivos en una estructura de carpetas, y el notebook en el que has trabajado me lo tienes sin nombre 🥲 , pero bueno son cositas que con el tiempo saldrán solas, me ha gustado que has trabajado desde python y has sabido encriptar la contraseña para no subirla :), pasito a pasito se hace el caminito, esta semana a ponerse las pilas ehh, 💪

**Comment by luciaahab** [comment]
Buf, real. Al final ya ni sabía cómo organizar todo y lo subí a cholón.
thanks 🙏🏼
